import { Inter } from 'next/font/google';
import './globals.css';
import SideBar from './sidebar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex font-poppins">
          <SideBar></SideBar>
          <div className=" relative isolate after:absolute after:z-0 bg-cover bg-transparent mx-[35px] my-[23px] flex flex-col flex-1">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
